[project]
name = "stacksgives-crowdfunding"
description = "Decentralized crowdfunding platform on Stacks blockchain"
authors = ["StacksGives Team"]
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.crowdfunding]
path = "contracts/crowdfunding.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2
